# Generated by Django 6.0.3 on 2026-03-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('physics_chemistry_biology', '物理・化学・生物'), ('hygiene', '衛生'), ('pharmacology', '薬理'), ('pharmaceutics', '薬剤'), ('pathology', '病態・薬物治療'), ('law_ethics', '法規・制度・倫理'), ('practice', '実務')], default='pharmacology', max_length=50),
            preserve_default=False,
        ),
    ]
