# Generated by Django 6.0.3 on 2026-03-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('required', '必須問題'), ('general', '一般問題')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(max_length=10),
        ),
    ]
