# Generated by Django 5.2.17 on 2026-09-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_question_type_alter_question_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
