# Generated by Django 6.1.1 on 2026-09-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_question_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice5',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='choice6',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
