# Generated by Django 6.1.1 on 2026-09-13 06:27

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_choice5_question_choice6'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='問題図（PNG・JPEG・WebP、5MB以下）。省略できます。', null=True, upload_to='questions/', validators=[quiz.models.validate_question_image_size]),
        ),
    ]
