# Generated by Django 5.0.4 on 2026-09-09 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('body', models.TextField(help_text='改行を反映します。HTMLタグは使用できません。', verbose_name='本文')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開する')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='未来の日時を指定すると、その日時から表示されます。', verbose_name='公開日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'ordering': ['-published_at', '-pk'],
            },
        ),
    ]
